### ISSUE TITLE
Add support for vuejs n nuxtjs

### ISSUE THREAD

**Issue by m4rcTr3y** [digitalocean/do-markdownit#24]
Is there a way how to configure this markdown engine with vuejs or nuxt?

**Comment by MattIPv4** [comment]
👋 Hey @m4rcTr3y, could you give some more context to what you're asking here?

This project is just a plugin, an extension, for the markdown-it library.

You'll want to find a Vue/Nuxt project that integrates markdown-it in Vue/Nuxt (or you can probably just call markdown-it yourself directly and inject raw HTML into Vue).

Our plugin just extends the functionality of markdown-it, it doesn't provide integration with frameworks.

**Comment by MattIPv4** [comment]
No progress, closing.
