### ISSUE TITLE
Help me show "copy"

### ISSUE THREAD

**Issue by quyphan97** [digitalocean/do-markdownit#27]
How can I display the copy button like above? please help me!
![image](https://user-images.githubusercontent.com/59947963/190091980-059ac3ff-516f-4cf5-8634-9510263928eb.png)

**Comment by quyphan97** [comment]
![image](https://user-images.githubusercontent.com/59947963/190114336-d837d3a2-dcb5-4332-ae46-a0248d37e1e1.png)

I tried doing that but it still doesn't work, am I doing it wrong?

**Comment by quyphan97** [comment]
Yes, thank you very much, I did it <3

**Comment by quyphan97** [comment]
Please allow me to close the issue

**Comment by quyphan97** [comment]
![image](https://user-images.githubusercontent.com/59947963/222097832-d372f40b-eaf5-470f-9dc3-2e6b34cf7a4f.png)

I used copy function and copy result it added 2 blank lines like picture
Please help me :((

**Comment by MattIPv4** [comment]
You may want to use a custom copy plugin that trims the content before it injects it into the clipboard.

**Comment by quyphan97** [comment]
@MattIPv4 Can you give me an example? please :((

**Comment by MattIPv4** [comment]
The original plugin can be found here: https://github.com/PrismJS/prism/blob/master/plugins/copy-to-clipboard/prism-copy-to-clipboard.js

You'd essentially want to change the logic within `getText` to whatever else you wanted (e.g. stripping trailing whitespace):

https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/plugins/copy-to-clipboard/prism-copy-to-clipboard.js#L129-L131

**Comment by quyphan97** [comment]
Well thank you very much

**Comment by MattIPv4** [comment]
The only caveat to that being if you write your own plugin, and want to use it in the same way as the vendored version of Prism we include in this package, you'll want to wrap it so you can pass a Prism instance in rather than relying on Prism being in a global scope.

You can see the wrapper we apply to the default Prism plugins here: https://github.com/digitalocean/do-markdownit/blob/a58ac7792813679bcbbf2b78bc746472b31d934f/script/prism.js#L88

**Comment by quyphan97** [comment]
Hi @MattIPv4, I can you help me copy this? I upgraded to version 1.12.0 and now the copy button is no longer displayed like before. I don't know what to configure in next.config or not.

![image](https://github.com/digitalocean/do-markdownit/assets/59947963/de61b016-5cf0-4f1d-9759-e2bd20939253)

**Comment by MattIPv4** [comment]
Hey, I'm not really in a position to continually debug your code. What version were you using before? Did you update anything else at the same time?

**Comment by quyphan97** [comment]
Yes, I'm sorry for bothering you.
