### ISSUE TITLE
Please add support in ReactJS & Typescript

### ISSUE THREAD

**Issue by quyphan97** [digitalocean/do-markdownit#4]
I tried library in ReactJS & Typescript but it doesn't seem to support
please add support in ReactJS & Typescript

**Comment by MattIPv4** [comment]
👋 @quyphan97 Please could you be more descriptive about what issue you're facing when using this with React/TS? We're using this with React ourselves and aren't running into any issues -- is it just a case of typings missing?

**Comment by quyphan97** [comment]
I used Typescript and ran the command `npm i --save-dev @styles/digitalocean__do-markdownit` but it could not install.
Looks like `@styles/digitalocean__do-markdownit` doesn't exist

**Comment by MattIPv4** [comment]
This package does not contain any styles, this is just a set of plugins to extend the rendering functionality of markdown-it.

**Comment by MattIPv4** [comment]
I'm going to close this out as this issue seems to around thinking this package is something it is not -- feel free to re-open if I'm misunderstanding.

**Comment by quyphan97** [comment]
Yes, thank you so much for supporting me. I will look for another approach
